apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: sample-cluster
spec:
  # version: v6.1.0
  pd:
    baseImage: pingcap/pd
    replicas: 3
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    requests:
      storage: "10Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 3
    service:
      # ロードバランサー経由でTiDBにアクセスすることが可能
      type: LoadBalancer
    config: {}
