apiVersion: v1
kind: Pod
metadata:
  name: tidb-client
spec:
  containers:
  - image: mysql:5.7
    name: tidb-client
    args:
    - sleep
    - "1000"
    resources: {}
    envFrom:
    - secretRef:
        name: tidb-config
    volumeMounts:
    - mountPath: /etc/tidb-ca
      name: tidb-ca
      readOnly: true
  volumes:
  - name: tidb-ca
    secret:
      secretName: tidb-ca
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
