apiVersion: v1
kind: Pod
metadata:
  name: helper
  namespace: mf
spec:
  containers:
  - name: helper
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: csv-processing-pvc
  restartPolicy: Never
