apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-processing-pvc
  namespace: mf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
