apiVersion: batch/v1
kind: Job
metadata:
  name: sjis2utf8-job
  namespace: mf
spec:
  # Job完了後も手動削除するまで残す（ログ確認のため）
  ttlSecondsAfterFinished: 3600  # 1時間後に自動削除
  backoffLimit: 3  # 最大3回リトライ
  template:
    metadata:
      labels:
        app: csv-converter
    spec:
      restartPolicy: OnFailure
      containers:
      - name: converter
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          #!/bin/sh
          set -e
          echo "Starting SJIS to UTF-8 conversion..."
          echo "INPUT_DIR: $INPUT_DIR"
          echo "OUTPUT_DIR: $OUTPUT_DIR"
          echo "FILE_NAME: $FILE_NAME"
          mkdir -p "${OUTPUT_DIR}"

          if [ -z "${FILE_NAME}" ]; then
            echo "Error: FILE_NAME environment variable is not set."
            exit 1
          fi
          tail -n +2 "${INPUT_DIR}/${FILE_NAME}" | iconv -f SJIS -t UTF-8 > "${OUTPUT_DIR}/${FILE_NAME%.csv}-utf8.csv"
          echo "Conversion completed successfully."
        env:
        - name: INPUT_DIR
          value: "/data/sjis-csv"
        - name: OUTPUT_DIR
          value: "/data/utf8-csv"
        - name: FILE_NAME
          value: "transactions.csv"
        volumeMounts:
        - name: shared-data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: csv-processing-pvc
